SET IDENTITY_INSERT [dbo].[Meals] ON
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (1, N'Margherita', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (2, N'Capriciosa', N'szynka, pieczarki', CAST(15.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (6, N'Italia', N'salami, pieczarki', CAST(15.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (8, N'Hawajska', N'szynka, ananas', CAST(15.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (9, N'Roma', N'salami, szynka, rukola', CAST(16.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (10, N'Tuna', N'tuńczyk, oliwki,cebula', CAST(16.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (11, N'Chicken', N'kurczak, pomidor, kukurydza', CAST(17.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (12, N'Kebab', N'kebab, papryka, cebula', CAST(17.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (13, N'Pepperoni', N'salami, papryka pepperoni, pieczarki', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (14, N'Favore', N'bekon, kurczak, papryka', CAST(17.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (15, N'Mamma Mia', N'szynka, pomido, oliwki, cebula, rukola', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (16, N'Grecka', N'feta, pomidor, oliwki, cebula', CAST(16.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (17, N'Farmerska', N'bekon, kiełbasa, papryka, ogórek konserwowy, cebula', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (18, N'Mexicana', N'wołowina, ostra papryka, czerwona fasola, kukurydza', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (19, N'Shrimp', N'krewetki, papryka, czosnek, cebula', CAST(20.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (20, N'Quatro Fromaggi', N'ser mozzarella, gouda, pleśniowy, feta', CAST(19.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (22, N'Vegetariana', N'papryka, pomidor, broluły, kukurydza, cebula', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (23, N'Sorrento', N'ser pleśniowy, szynka, papryka, pomidory suszone, kapary', CAST(20.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (24, N'Diablo', N'salami, papryka jalapeno, papryka peperoni, ser Grana Padano, sos ostry sambal', CAST(22.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (25, N'Toscana', N'szynka parmeńskam, ser mozzarella, oliwki, pomidor, rukola', CAST(22.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (26, N'Moja Fantazja', N'5 dowolnych składników ', CAST(22.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (28, N'pieczarki', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (29, N'rukola', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (31, N'oliwki', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (32, N'cebula', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (33, N'pomidor', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (34, N'kukurydza', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (35, N'papryka', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (36, N'kapary', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (37, N'ogórek konserwowy', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (38, N'czosnek', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (39, N'czerwona fasola', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (40, N'brokuły', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (41, N'ananas', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (42, N'szynka', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (43, N'salami ', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (44, N'kurczak', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (45, N'wołowina', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (46, N'kebab', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (47, N'bekon', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (48, N'kiełbasa', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (49, N'tuńczyk', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (50, N'suszone pomidory', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (51, N'papryka jalapeno', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (52, N'feta', NULL, CAST(3.00 AS Decimal(18, 2)), N'', N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (53, N'ser pleśniowy', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (54, N'gouda', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (55, N'mozzarella', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (56, N'grana padano', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (57, N'krewetki', NULL, CAST(6.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (58, N'szynka parmeńska', NULL, CAST(6.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (60, N'Kebab duży', NULL, CAST(14.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (61, N'Kebab mały', NULL, CAST(11.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (62, N'Kebab Grecki duży', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (63, N'Kebab Grecki mały', NULL, CAST(13.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (64, N'Kebab Chilli duży', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (65, N'Kebab Chilli mały', NULL, CAST(13.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (66, N'Kebab Rollo (w tortilli)', NULL, CAST(13.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (67, N'Zapiekanka z kurczakiem', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (68, N'Zapiekanka z pieczarkami', N'', CAST(10.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (69, N'Zapiekanka z pieczarkami', NULL, CAST(10.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (70, N'Zapiekanka z Chilli Con Carne', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (82, N'Burito z kurczakiem', N'farsz z mięsa, warzywm ryżu zawinięty w tortille', CAST(13.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (84, N'Burito z wołowiną', N'farsz z mięsa, warzywm ryżu zawinięty w tortille', CAST(13.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (85, N'Chilli con Carne z grznkami czosnkowymi', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (86, N'Fajita Cerdo', N'schab z grilla krojony w paski, papryka, cebula zawiniętą w tortillę podawany z gucamole, salsą, i kwaśną śmietaną', CAST(17.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (88, N'Fajita Pollo', N'pierś z grilla krojona w paski, papryka, cebula zawinięta w tortillę podawana z gucamole, salsą i kwaśna śmietaną', CAST(17.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (89, N'Caprese', N'mozarella, pomidor, kapary, sałata lodowa, oliwa, grzanka czosnkowa', CAST(15.00 AS Decimal(18, 2)), NULL, N'Sałatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (90, N'Grecka', N'feta, oliwki, czerwona cebula, ogórek, pomidor, sałata lodowa, sos vinegrette i grzanka czosnkowa', CAST(15.00 AS Decimal(18, 2)), NULL, N'Sałatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (92, N'Don''kogutto', N'grillowana pierś kurczaka, pomidor, mango, sałata lodowa, czerwona cebula, klendra, sos miodowo-musztardowy i grzanka czosnkowa', CAST(18.00 AS Decimal(18, 2)), NULL, N'Sałatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (93, N'Nuggetsy', N'6szt', CAST(8.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (94, N'Gyros', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (96, N'Pierś kurczaka z grilla ', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (97, N'Pierś kurczaka z masłem czosnkowym z grilla ', NULL, CAST(9.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (98, N'Pierś kurczaka po hawajsku', N'z ananasem i serem', CAST(10.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (99, N'Karkówka Mucho Macho z grilla', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (100, N'Hamburger Texas', N'grillowany wołowy stek mielony i bekon, warzywa, podawany w bułce', CAST(12.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (101, N'Cheese Burger Texas', N'grillowany wołowy stek mielony z serem i bekon, warzywa, podawany w bułce', CAST(13.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (102, N'Chicken Burger Texas', N'grillowana pierś z kurczaka i bekon, warzywa, podawany w bułce', CAST(13.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (104, N'Krewetki w sosie Mojo', N'8szt', CAST(16.00 AS Decimal(18, 2)), NULL, N'Owoce morza')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (105, N'Makaron Tagliatelle ze szpinakiem i migdałami', NULL, CAST(15.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (106, N'Makaron Tagliatelle Carbonara', NULL, CAST(15.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (107, N'Makaron Tagliatelle Bolognese', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (108, N'Magaron Tagliatelle z kurczakiem i brokułami w sosie śmietanowym', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (109, N'Makaron Tagiatelle z Chilli Con Carne', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (110, N'Makaron Tagiatelle z łososiem w sosie śmietanowo-lazurowym', NULL, CAST(24.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (111, N'Tortilla', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (112, N'Frytki', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (113, N'Ryż', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (114, N'Grzanki z masłem czosnkowym i serem (duża)', NULL, CAST(7.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (115, N'Surówla', NULL, CAST(4.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (116, N'Salsa Mexicana ', NULL, CAST(4.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (117, N'Guacamole', NULL, CAST(4.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (118, N'Ostry sambal', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (119, N'Czosnkowy', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (120, N'Ketchup', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (121, N'Musztarda', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (122, N'Kwaśna śmietana', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (123, N'Kawa', NULL, CAST(7.00 AS Decimal(18, 2)), NULL, N'Napoje gorące')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (124, N'Capuccino', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Napoje gorące')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (125, N'Herbata', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje gorące')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (126, N'Coca-Cola 0,5l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (127, N'Fanta 0,5l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (128, N'Sprite 0,5l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (129, N'Woda 0,5l', NULL, CAST(3.50 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (130, N'Cappy 0,33l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (131, N'Powerade 0,5l', NULL, CAST(7.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ([MealID], [Name], [Description], [Price], [ImageName], [Category]) VALUES (132, N'Red Bull ', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
SET IDENTITY_INSERT [dbo].[Meals] OFF
