SET IDENTITY_INSERT [dbo].[Meals] ON
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES (N'Margherita', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES (N'Capriciosa', N'szynka, pieczarki', CAST(15.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES (N'Italia', N'salami, pieczarki', CAST(15.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES (N'Hawajska', N'szynka, ananas', CAST(15.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES (N'Roma', N'salami, szynka, rukola', CAST(16.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Tuna', N'tuńczyk, oliwki,cebula', CAST(16.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Chicken', N'kurczak, pomidor, kukurydza', CAST(17.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab', N'kebab, papryka, cebula', CAST(17.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Pepperoni', N'salami, papryka pepperoni, pieczarki', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Favore', N'bekon, kurczak, papryka', CAST(17.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Mamma Mia', N'szynka, pomido, oliwki, cebula, rukola', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Grecka', N'feta, pomidor, oliwki, cebula', CAST(16.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Farmerska', N'bekon, kiełbasa, papryka, ogórek konserwowy, cebula', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Mexicana', N'wołowina, ostra papryka, czerwona fasola, kukurydza', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Shrimp', N'krewetki, papryka, czosnek, cebula', CAST(20.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Quatro Fromaggi', N'ser mozzarella, gouda, pleśniowy, feta', CAST(19.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Vegetariana', N'papryka, pomidor, broluły, kukurydza, cebula', CAST(18.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Sorrento', N'ser pleśniowy, szynka, papryka, pomidory suszone, kapary', CAST(20.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Diablo', N'salami, papryka jalapeno, papryka peperoni, ser Grana Padano, sos ostry sambal', CAST(22.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Toscana', N'szynka parmeńskam, ser mozzarella, oliwki, pomidor, rukola', CAST(22.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Moja Fantazja', N'5 dowolnych składników ', CAST(22.00 AS Decimal(18, 2)), NULL, N'Pizza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'pieczarki', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'rukola', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'oliwki', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'cebula', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'pomidor', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'kukurydza', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'papryka', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'kapary', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'ogórek konserwowy', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'czosnek', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'czerwona fasola', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'brokuły', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'ananas', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'szynka', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'salami ', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'kurczak', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'wołowina', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'kebab', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'bekon', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'kiełbasa', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'tuńczyk', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'suszone pomidory', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'papryka jalapeno', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'feta', NULL, CAST(3.00 AS Decimal(18, 2)), N'', N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'ser pleśniowy', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'gouda', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'mozzarella', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'grana padano', NULL, CAST(3.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'krewetki', NULL, CAST(6.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'szynka parmeńska', NULL, CAST(6.00 AS Decimal(18, 2)), NULL, N'dodatki do pizzy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab duży', NULL, CAST(14.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab mały', NULL, CAST(11.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab Grecki duży', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab Grecki mały', NULL, CAST(13.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab Chilli duży', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab Chilli mały', NULL, CAST(13.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kebab Rollo (w tortilli)', NULL, CAST(13.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Zapiekanka z kurczakiem', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Zapiekanka z pieczarkami', N'', CAST(10.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Zapiekanka z pieczarkami', NULL, CAST(10.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Zapiekanka z Chilli Con Carne', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Fast Food')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Burito z kurczakiem', N'farsz z mięsa, warzywm ryżu zawinięty w tortille', CAST(13.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Burito z wołowiną', N'farsz z mięsa, warzywm ryżu zawinięty w tortille', CAST(13.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Chilli con Carne z grznkami czosnkowymi', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Fajita Cerdo', N'schab z grilla krojony w paski, papryka, cebula zawiniętą w tortillę podawany z gucamole, salsą, i kwaśną śmietaną', CAST(17.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Fajita Pollo', N'pierś z grilla krojona w paski, papryka, cebula zawinięta w tortillę podawana z gucamole, salsą i kwaśna śmietaną', CAST(17.00 AS Decimal(18, 2)), NULL, N'Nasze Specjały')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Caprese', N'mozarella, pomidor, kapary, sałata lodowa, oliwa, grzanka czosnkowa', CAST(15.00 AS Decimal(18, 2)), NULL, N'Sałatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Grecka', N'feta, oliwki, czerwona cebula, ogórek, pomidor, sałata lodowa, sos vinegrette i grzanka czosnkowa', CAST(15.00 AS Decimal(18, 2)), NULL, N'Sałatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Don''kogutto', N'grillowana pierś kurczaka, pomidor, mango, sałata lodowa, czerwona cebula, klendra, sos miodowo-musztardowy i grzanka czosnkowa', CAST(18.00 AS Decimal(18, 2)), NULL, N'Sałatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Nuggetsy', N'6szt', CAST(8.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Gyros', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Pierś kurczaka z grilla ', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Pierś kurczaka z masłem czosnkowym z grilla ', NULL, CAST(9.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Pierś kurczaka po hawajsku', N'z ananasem i serem', CAST(10.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Karkówka Mucho Macho z grilla', NULL, CAST(12.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Hamburger Texas', N'grillowany wołowy stek mielony i bekon, warzywa, podawany w bułce', CAST(12.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Cheese Burger Texas', N'grillowany wołowy stek mielony z serem i bekon, warzywa, podawany w bułce', CAST(13.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Chicken Burger Texas', N'grillowana pierś z kurczaka i bekon, warzywa, podawany w bułce', CAST(13.00 AS Decimal(18, 2)), NULL, N'Mięsa')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Krewetki w sosie Mojo', N'8szt', CAST(16.00 AS Decimal(18, 2)), NULL, N'Owoce morza')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Makaron Tagliatelle ze szpinakiem i migdałami', NULL, CAST(15.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Makaron Tagliatelle Carbonara', NULL, CAST(15.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Makaron Tagliatelle Bolognese', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Magaron Tagliatelle z kurczakiem i brokułami w sosie śmietanowym', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Makaron Tagiatelle z Chilli Con Carne', NULL, CAST(16.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Makaron Tagiatelle z łososiem w sosie śmietanowo-lazurowym', NULL, CAST(24.00 AS Decimal(18, 2)), NULL, N'Pasty')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Tortilla', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Frytki', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Ryż', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Grzanki z masłem czosnkowym i serem (duża)', NULL, CAST(7.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Surówla', NULL, CAST(4.00 AS Decimal(18, 2)), NULL, N'Dodatki')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Salsa Mexicana ', NULL, CAST(4.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Guacamole', NULL, CAST(4.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Ostry sambal', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Czosnkowy', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Ketchup', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Musztarda', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kwaśna śmietana', NULL, CAST(2.00 AS Decimal(18, 2)), NULL, N'Sosy')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Kawa', NULL, CAST(7.00 AS Decimal(18, 2)), NULL, N'Napoje gorące')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Capuccino', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Napoje gorące')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Herbata', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje gorące')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Coca-Cola 0,5l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Fanta 0,5l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Sprite 0,5l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Woda 0,5l', NULL, CAST(3.50 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Cappy 0,33l', NULL, CAST(5.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Powerade 0,5l', NULL, CAST(7.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
INSERT INTO [dbo].[Meals] ( [Name], [Description], [Price], [ImageName], [Category]) VALUES ( N'Red Bull ', NULL, CAST(8.00 AS Decimal(18, 2)), NULL, N'Napoje zimne')
SET IDENTITY_INSERT [dbo].[Meals] OFF
